### ISSUE TITLE
db operation should be done on class objects rather than session

### ISSUE THREAD

**Issue by rajeevkumarsharma** [artifacthealth/hydrate-mongodb#1]
Operation on documents should be done directly rather than session

ex.

let dog = new Dog({name: 'Tommy'}) 
dog.save() //currently it is session.save(dog) ;

If possible use Observable instead of promises/callback.

**Comment by meirgottlieb** [comment]
@rajeevkumarsharma Thanks for the feedback. This was a design decision to use the session for operations, similar to [Hibernate](http://hibernate.org/orm/), rather than the entity instance. It allows for some optimizations such as bulk write operations. 

There are lots of other projects that use the approach you suggest. Take a look at [Iridium](https://github.com/SierraSoftworks/Iridium).
