### ISSUE TITLE
Annotations outside of my entities

### ISSUE THREAD

**Issue by StephanyBatista** [artifacthealth/hydrate-mongodb#11]
Hello, 

How I can write code with the annotations outside of my entities? By example, in .Net we can not write annotation in our entity, but we must configure as Fluent API. 

Why this?

When I use mutation testing or code coverage there are code that I do not write and the tools complains.

**Comment by meirgottlieb** [comment]
Are you asking if there is a way to configure the entities without annotations? The issue is that TypeScript does not make the type information available at run-time unless the class is annotated. So you would end up doing double work having to specify all fields and their types. 

If the problem is that the code that TypeScript generates to support the annotaitons is showing up in your code coverage, try remapping your code coverage using source maps. Take a look at [remap-istanbul](https://www.npmjs.com/package/remap-istanbul).
