### ISSUE TITLE
Experimental status

### ISSUE THREAD

**Issue by rcorrear** [artifacthealth/hydrate-mongodb#3]
Hi,

I'd love to use this project for a new development but I'm skeptical because of this: "Hydrate is an experimental project and is not recommended for production systems.". This project will enter heavy production use in a couple months and obviously something unstable would be out of the question, but at the same time there's nothing like it in TypeScript (that I know of and I've been looking).

That said, the obvious question is, does that warning still hold true? Is there a roadmap to a stable version (both for the API and for the code)? All of that said, the project looks great, thanks!

**Comment by meirgottlieb** [comment]
Hey @rcorrear - I plan on lifting that 'experimental' label in about a month. I do plan on some breaking changes soon but nothing too crazy. I'm probably going to get rid of the `getIdentifier` function and just make the `@Id` decorator required.

**Comment by meirgottlieb** [comment]
FYI, Hydrate is now at 1.0.0 and the 'experimental' status has been removed. There is one breaking change in moving to 1.0.0 similar to what I described above. However, instead of making the @Id decorator required, I removed the @Id decorator and made the default behavior adding an `id` property to every entity with the string representation of the identifier.
